### ISSUE TITLE
Game loop

### ISSUE THREAD

**Issue by veronika-luthar** [douai724/StudyDungeon#12]

**Comment by veronika-luthar** [comment]
The turn based gameplay between the player and the enemy

**Comment by murraycadzow** [comment]
Features to expand on for beta
- [ ] starting deck of 40 standard cards
- [ ] additional cards drawn based on difficulty of flashcards answered - eg RNG +1, +2, +3
- [ ] lose if run out of cards or health
- [ ] win if boss dies
- [ ] hand of 5, play 1 draw 1
